### ISSUE TITLE
Does NOT work on raspberry pi aarch64

### ISSUE THREAD

**Issue by jalapenopuzzle** [nickovs/atomicswap#1]
On raspberry pi (aarch64), when I try to use

atomicswap.swap(file_a, file_b)

I get an error
error [Errno 38] Function not implemented.

It seems that the syscall index for renameat2 on aarch64 is 276 [1], whereas it is 316 on x86_64 [2].

I changed it at atomicswap/linux.py:12
< SYSCALL_RENAMEAT2 = 316
> SYSCALL_RENAMEAT2 = 276

That was enough to make it work on aarch64 (but this won't work on x86_64).

However, a more general solution is required to cater for multiple architectures.

[1] https://arm64.syscall.sh/
[2] https://hackeradam.com/x86-64-linux-syscalls/

**Comment by nickovs** [comment]
Thanks for this. It's very helpful. I will look into a reliable way to detect architecture and handle this.

**Comment by nickovs** [comment]
@jalapenopuzzle I've added multi-architecture support and tested it on `aarch64` and `arm7l`, which cover 64-bit and 32-bit Raspberry Pis respectively. There's also untested support for `i386`, in case someone is running old-school PC hardware.

The changes make it easy to [add support](https://github.com/nickovs/atomicswap/blob/973aca971f9c0d0903e24520de57e9b10243b4b7/src/atomicswap/linux.py#L11-L16) for other Linux platforms as long as someone can report what `platform.machine()` returns for a given system and match it to an entry in [this table](https://marcin.juszkiewicz.com.pl/download/tables/syscalls.html) of syscalls

The changes are now available on [PyPI](https://pypi.org/project/atomicswap/) as version 0.2.1.
